{% set name = "osg2vsg" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/vsg-dev/osg2vsg/archive/v{{ version }}.tar.gz
    sha256: 784ca5b8712fa66207bafcf6e71d41494e82d0a0ee65aa75cec6f8ebbc6a28f0

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('osg2vsg', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [unix]
    - pkgconfig  # [linux]
  host:
    - libgl-devel  # [linux]
    - libvulkan-headers
    - libvulkan-loader
    - openscenegraph
    - vulkanscenegraph
  run:
    - libvulkan-loader
    - vulkanscenegraph

test:
  commands:
    - test -f $PREFIX/include/osg2vsg/Export.h  # [unix]
    - test -f $PREFIX/lib/libosg2vsg${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/cmake/osg2vsg/osg2vsgConfig.cmake  # [unix]
    - if not exist %PREFIX%\\Library\\include\\osg2vsg\\Export.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\osg2vsg.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\osg2vsg.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\osg2vsg\\osg2vsgConfig.cmake exit 1  # [win]

about:
  home: https://vsg-dev.github.io/vsg-dev.io/
  summary: Adapter library for converting OpenSceneGraph Images and 3D models to VulkanSceneGraph
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/vsg-dev/osg2vsg

extra:
  recipe-maintainers:
    - jeongseok-meta
