context:
  name: osg2vsg
  version: "0.3.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/vsg-dev/osg2vsg/archive/v${{ version }}.tar.gz
  sha256: 784ca5b8712fa66207bafcf6e71d41494e82d0a0ee65aa75cec6f8ebbc6a28f0
  patches:
    - patches/0001-Use-current-vsg-mipmap-property.patch

build:
  number: 2
  script:
    - if: win
      then: call "%RECIPE_DIR%\\build.bat"
    - if: unix
      then: bash "${RECIPE_DIR}/build.sh"

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: unix
      then: ninja
    - if: linux
      then: pkgconfig
  host:
    - if: linux
      then: libgl-devel
    - libvulkan-headers
    - libvulkan-loader
    - openscenegraph
    - vulkanscenegraph
  run_exports:
    - ${{ pin_subpackage('osg2vsg', upper_bound='x.x') }}
  ignore_run_exports:
    from_package:
      - libgl-devel
      - libvulkan-loader

tests:
  - requirements:
      run:
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake
        - if: unix
          then: ninja
        - if: linux
          then: pkgconfig
    files:
      recipe:
        - run_test.bat
        - run_test.sh
        - tests/
    script:
      - if: unix
        then:
          - test -f "${PREFIX}/include/osg2vsg/Export.h"
          - test -f "${PREFIX}/lib/libosg2vsg${SHLIB_EXT}"
          - test -f "${PREFIX}/lib/cmake/osg2vsg/osg2vsgConfig.cmake"
          - bash run_test.sh
      - if: win
        then:
          - if not exist "%PREFIX%\\Library\\include\\osg2vsg\\Export.h" exit 1
          - if not exist "%PREFIX%\\Library\\lib\\osg2vsg.lib" exit 1
          - if not exist "%PREFIX%\\Library\\bin\\osg2vsg.dll" exit 1
          - if not exist "%PREFIX%\\Library\\lib\\cmake\\osg2vsg\\osg2vsgConfig.cmake" exit 1
          - call run_test.bat

about:
  homepage: https://vsg-dev.github.io/vsg-dev.io/
  repository: https://github.com/vsg-dev/osg2vsg
  summary: Adapter library for converting OpenSceneGraph Images and 3D models to VulkanSceneGraph
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jeongseok-meta
